/**
 * Điểm "cắm" repository duy nhất của ứng dụng (composition root cho lớp dữ liệu).
 * Thay bằng implementation database tại đây mà không phải sửa service hay UI.
 */
import {
  jsonAnalyticsRepository,
  jsonChatAliasRepository,
  jsonDataReportRepository,
  jsonNotificationRepository,
  jsonReminderLogRepository,
  jsonSurveyRepository,
  jsonTimelineConfigRepository,
  jsonAuditRepository,
  jsonChatLogRepository,
  jsonCommentRepository,
  jsonOutcomeRepository,
  jsonReviewRepository,
  jsonProgramAdminRepository,
  jsonProgramRepository,
  jsonShareRepository,
  jsonUserDataRepository,
  jsonUserRepository,
  jsonQaRepository,
  jsonClassRepository,
  jsonOutcomeSurveyRepository,
  jsonSchoolRepository,
  jsonMajorRepository,
  jsonQuizRepository,
  jsonCatalogAdminRepository,
  jsonQuizConfigRepository,
  jsonRecommendConfigRepository,
  jsonImportBatchRepository,
  jsonSchoolSubmissionRepository,
} from "./json-file";
import { memoryCatalogRepository, memoryTimelineRepository } from "./memory";

export const repositories = {
  /** Dữ liệu gốc + phần quản trị viên thêm/sửa/ẩn. */
  schools: jsonSchoolRepository,
  majors: jsonMajorRepository,
  /** Dữ liệu gốc + phần quản trị viên đã chỉnh. */
  programs: jsonProgramRepository,
  programAdmin: jsonProgramAdminRepository,
  catalog: memoryCatalogRepository,
  quiz: jsonQuizRepository,
  catalogAdmin: jsonCatalogAdminRepository,
  quizConfig: jsonQuizConfigRepository,
  recommendConfig: jsonRecommendConfigRepository,
  importBatches: jsonImportBatchRepository,
  schoolSubmissions: jsonSchoolSubmissionRepository,
  timeline: memoryTimelineRepository,
  users: jsonUserRepository,
  userData: jsonUserDataRepository,
  shares: jsonShareRepository,
  comments: jsonCommentRepository,
  audit: jsonAuditRepository,
  outcomes: jsonOutcomeRepository,
  reviews: jsonReviewRepository,
  chatLogs: jsonChatLogRepository,
  dataReports: jsonDataReportRepository,
  notifications: jsonNotificationRepository,
  timelineConfig: jsonTimelineConfigRepository,
  chatAliases: jsonChatAliasRepository,
  analytics: jsonAnalyticsRepository,
  surveys: jsonSurveyRepository,
  reminderLog: jsonReminderLogRepository,
  qa: jsonQaRepository,
  classes: jsonClassRepository,
  outcomeSurveys: jsonOutcomeSurveyRepository,
};

export type Repositories = typeof repositories;
export type {
  AuditRepository,
  CatalogRepository,
  ChatLogRepository,
  OutcomeRepository,
  ReviewRepository,
  CommentRepository,
  MajorRepository,
  ProgramAdminRepository,
  ProgramRepository,
  QuizRepository,
  SchoolRepository,
  ShareRepository,
  TimelineRepository,
  UserDataRepository,
  UserRepository,
} from "./types";
