import { writeFileSync } from "node:fs";
import { join } from "node:path";
import type { School, Major, Program, Specialization, RiasecType, AdmissionMethod, Competition, MethodCutoff, Combo, Subject } from "../src/domain/types";

// ============================================================================
// 1. TOÀN BỘ DANH SÁCH TRƯỜNG ĐẠI HỌC, HỌC VIỆN & CAO ĐẲNG TOÀN QUỐC (60+ TRƯỜNG ĐẦU NGÀNH)
// ============================================================================
export const nationalSchools: School[] = [
  // ── MIỀN BẮC (Hà Nội, Hải Phòng, Hưng Yên, Vĩnh Phúc, v.v.) ───────────────
  {
    id: "hust", slug: "dai-hoc-bach-khoa-ha-noi", code: "BKA", name: "Đại học Bách khoa Hà Nội", shortName: "ĐH Bách khoa Hà Nội",
    type: "cong-lap", level: "dai-hoc", region: "bac", city: "Hà Nội", founded: 1956, students: 35000, highlight: "Top 1 Kỹ thuật & Công nghệ miền Bắc",
    campuses: ["Số 1 Đại Cồ Việt, Hai Bà Trưng, Hà Nội", "Khu Công nghệ cao Hòa Lạc, Thạch Thất, Hà Nội"], website: "https://hust.edu.vn",
    description: "Trường đại học kỹ thuật đa ngành hàng đầu Việt Nam, thế mạnh vượt trội về CNTT, Khoa học máy tính, Cơ điện tử, Vi mạch bán dẫn và Tự động hóa.",
    scholarships: "Học bổng khuyến khích 10-100% học phí, học bổng tài năng thủ khoa, tài trợ doanh nghiệp (Samsung, Viettel, FPT).",
    aliases: ["dhbk", "đhbk", "dhbkhn", "bkhn", "bk ha noi", "hust", "bka", "bach khoa ha noi", "bach khoa"],
  },
  {
    id: "neu", slug: "dai-hoc-kinh-te-quoc-dan", code: "KHA", name: "Đại học Kinh tế Quốc dân", shortName: "ĐH Kinh tế Quốc dân",
    type: "cong-lap", level: "dai-hoc", region: "bac", city: "Hà Nội", founded: 1956, students: 30000, highlight: "Top 1 khối Kinh tế & Quản trị",
    campuses: ["207 Giải Phóng, Đồng Tâm, Hai Bà Trưng, Hà Nội"], website: "https://neu.edu.vn",
    description: "Trường đại học trọng điểm quốc gia về kinh tế, quản lý và quản trị kinh doanh; tiên phong chương trình liên kết quốc tế và đào tạo chất lượng cao.",
    scholarships: "Học bổng khuyến khích học tập, Quỹ học bổng Tài năng NEU, học bổng Big4 kiểm toán và các ngân hàng lớn.",
    aliases: ["dhktqd", "đhktqd", "ktqd", "neu", "kha", "kinh te quoc dan", "dh kinh te quoc dan"],
  },
  {
    id: "ftu", slug: "truong-dai-hoc-ngoai-thuong", code: "NTH", name: "Trường Đại học Ngoại thương", shortName: "ĐH Ngoại thương",
    type: "cong-lap", level: "dai-hoc", region: "bac", city: "Hà Nội", founded: 1960, students: 18000, highlight: "Top 1 Kinh tế đối ngoại & Kinh doanh quốc tế",
    campuses: ["91 Chùa Láng, Láng Thượng, Đống Đa, Hà Nội", "Cơ sở II: 15 Đường D5, P. 25, Bình Thạnh, TP. Hồ Chí Minh", "Cơ sở Quảng Ninh: 260 Bạch Đằng, Uông Bí, Quảng Ninh"], website: "https://ftu.edu.vn",
    description: "Cái nôi đào tạo chuyên gia kinh tế đối ngoại, kinh doanh quốc tế, tài chính quốc tế và khởi nghiệp sáng tạo nổi tiếng năng động.",
    scholarships: "Học bổng khuyến khích học tập, học bổng từ hơn 60 tập đoàn đa quốc gia và cựu sinh viên.",
    aliases: ["dhnt", "đhnt", "ftu", "nth", "ngoai thuong", "ftu ha noi", "ftu hcm"],
  },
  {
    id: "uet", slug: "truong-dai-hoc-cong-nghe-dhqghn", code: "QHI", name: "Trường Đại học Công nghệ – ĐHQGHN", shortName: "ĐH Công nghệ – ĐHQGHN",
    type: "cong-lap", level: "dai-hoc", region: "bac", city: "Hà Nội", founded: 2004, students: 9500, highlight: "Top 1 Nghiên cứu Công nghệ & AI",
    campuses: ["144 Xuân Thủy, Cầu Giấy, Hà Nội", "Khu đô thị ĐHQGHN Hòa Lạc, Hà Nội"], website: "https://uet.vnu.edu.vn",
    description: "Trường thành viên nòng cốt của ĐHQG Hà Nội về khoa học công nghệ cao, AI, bán dẫn, công nghệ thông tin và robot học.",
    scholarships: "Học bổng tài năng ĐHQGHN, học bổng viện trợ từ Viettel, VNPT, Samsung, LG Display.",
    aliases: ["dhcn", "đhcn", "uet", "qhi", "cong nghe dhqg", "uet vnu"],
  },
  {
    id: "ussh", slug: "truong-dai-hoc-khxhnv-dhqghn", code: "QHX", name: "Trường ĐH Khoa học Xã hội và Nhân văn – ĐHQGHN", shortName: "ĐH KHXH&NV – ĐHQGHN",
    type: "cong-lap", level: "dai-hoc", region: "bac", city: "Hà Nội", founded: 1995, students: 13000, highlight: "Top 1 Khoa học Xã hội & Nhân văn",
    campuses: ["336 Nguyễn Trãi, Thanh Xuân Trung, Thanh Xuân, Hà Nội"], website: "https://ussh.vnu.edu.vn",
    description: "Trung tâm đào tạo và nghiên cứu hàng đầu về Báo chí, Truyền thông đa phương tiện, Quan hệ công chúng, Tâm lý học, Đông phương học và Ngôn ngữ.",
    scholarships: "Học bổng khuyến khích học tập, học bổng ĐHQGHN, học bổng các tổ chức quốc tế (KOICA, JICA, DAAD).",
    aliases: ["dhxhnv", "đhxhnv", "dhkhxhnv", "đhkhxhnv", "ussh", "qhx", "nhan van", "xa hoi nhan van", "ussh hn"],
  },
  {
    id: "hus", slug: "truong-dai-hoc-khoa-hoc-tu-nhien-dhqghn", code: "QHK", name: "Trường ĐH Khoa học Tự nhiên – ĐHQGHN", shortName: "ĐH Khoa học Tự nhiên – ĐHQGHN",
    type: "cong-lap", level: "dai-hoc", region: "bac", city: "Hà Nội", founded: 1956, students: 11000, highlight: "Cái nôi khoa học cơ bản hàng đầu",
    campuses: ["334 Nguyễn Trãi, Thanh Xuân, Hà Nội", "19 Lê Thánh Tông, Hoàn Kiếm, Hà Nội"], website: "https://hus.vnu.edu.vn",
    description: "Đào tạo các ngành khoa học cơ bản mũi nhọn: Toán - Tin, Hóa học, Sinh học, Khoa học Môi trường và Hải dương học.",
    scholarships: "Học bổng ươm mầm tài năng khoa học cơ bản ĐHQGHN (miễn học phí + trợ cấp sinh hoạt).",
    aliases: ["dhkhtn", "đhkhtn", "khtn", "hus", "qhk", "khoa hoc tu nhien"],
  },
  {
    id: "ulis", slug: "truong-dai-hoc-ngoai-ngu-dhqghn", code: "QHN", name: "Trường ĐH Ngoại ngữ – ĐHQGHN", shortName: "ĐH Ngoại ngữ – ĐHQGHN",
    type: "cong-lap", level: "dai-hoc", region: "bac", city: "Hà Nội", founded: 1955, students: 10000, highlight: "Hàng đầu đào tạo Ngoại ngữ & Sư phạm Ngoại ngữ",
    campuses: ["Số 2 Phạm Văn Đồng, Dịch Vọng Hậu, Cầu Giấy, Hà Nội"], website: "https://ulis.vnu.edu.vn",
    description: "Trung tâm đào tạo ngôn ngữ Anh, Trung, Nhật, Hàn, Pháp, Đức và sư phạm ngoại ngữ uy tín số 1 miền Bắc.",
    scholarships: "Học bổng ĐHQGHN, học bổng chính phủ trao đổi sinh viên nước ngoài.",
    aliases: ["dhnn", "đhnn", "ulis", "qhn", "ngoai ngu dhqg"],
  },
  {
    id: "ueb", slug: "truong-dai-hoc-kinh-te-dhqghn", code: "QHE", name: "Trường ĐH Kinh tế – ĐHQGHN", shortName: "ĐH Kinh tế – ĐHQGHN",
    type: "cong-lap", level: "dai-hoc", region: "bac", city: "Hà Nội", founded: 1974, students: 8000, highlight: "Quốc tế hóa đào tạo Kinh tế & Tài chính",
    campuses: ["144 Xuân Thủy, Cầu Giấy, Hà Nội"], website: "https://ueb.edu.vn",
    description: "Đào tạo cử nhân kinh tế quốc tế, quản trị kinh doanh, tài chính ngân hàng chuẩn quốc tế và liên kết Đại học Troy (Mỹ).",
    scholarships: "Học bổng UEB Pass, học bổng doanh nghiệp quốc tế.",
    aliases: ["ueb", "qhe", "kinh te dhqg", "dh kinh te dhqg"],
  },
  {
    id: "hmu", slug: "truong-dai-hoc-y-ha-noi", code: "YHB", name: "Trường Đại học Y Hà Nội", shortName: "ĐH Y Hà Nội",
    type: "cong-lap", level: "dai-hoc", region: "bac", city: "Hà Nội", founded: 1902, students: 12500, highlight: "Trường Đại học Y khoa số 1 Việt Nam",
    campuses: ["1 Tôn Thất Tùng, Kim Liên, Đống Đa, Hà Nội", "Phân hiệu Thanh Hóa: TP. Thanh Hóa"], website: "https://hmu.edu.vn",
    description: "Trường y khoa lâu đời và danh tiếng nhất Việt Nam, đào tạo Bác sĩ Y đa khoa, Răng - Hàm - Mặt, Y học cổ truyền, Kỹ thuật y học.",
    scholarships: "Học bổng khuyến khích học tập và học bổng từ các bệnh viện Trung ương hàng đầu.",
    aliases: ["dhy", "đhy", "dhyhn", "đhyhn", "yhn", "hmu", "yhb", "y ha noi"],
  },
  {
    id: "hup", slug: "truong-dai-hoc-duoc-ha-noi", code: "DKH", name: "Trường Đại học Dược Hà Nội", shortName: "ĐH Dược Hà Nội",
    type: "cong-lap", level: "dai-hoc", region: "bac", city: "Hà Nội", founded: 1961, students: 5000, highlight: "Trường Dược học trọng điểm quốc gia",
    campuses: ["13-15 Lê Thánh Tông, Phan Chu Trinh, Hoàn Kiếm, Hà Nội"], website: "https://hup.edu.vn",
    description: "Cơ sở đầu ngành về đào tạo Dược sĩ đại học, Hóa dược, Công nghệ dược phẩm và kiểm nghiệm chất lượng thuốc.",
    scholarships: "Học bổng khuyến khích học tập, học bổng các tập đoàn dược phẩm đa quốc gia.",
    aliases: ["dhdhn", "hup", "dkh", "duoc ha noi"],
  },
  {
    id: "hnue", slug: "truong-dai-hoc-su-pham-ha-noi", code: "SPH", name: "Trường Đại học Sư phạm Hà Nội", shortName: "ĐH Sư phạm Hà Nội",
    type: "cong-lap", level: "dai-hoc", region: "bac", city: "Hà Nội", founded: 1951, students: 22000, highlight: "Trường Sư phạm trọng điểm quốc gia",
    campuses: ["136 Xuân Thủy, Dịch Vọng Hậu, Cầu Giấy, Hà Nội"], website: "https://hnue.edu.vn",
    description: "Đào tạo giáo viên, giảng viên và chuyên gia giáo dục cho mọi cấp học từ Mầm non đến Đại học.",
    scholarships: "Hỗ trợ học phí & sinh hoạt phí theo Nghị định 116/2020 của Chính phủ.",
    aliases: ["dhsp", "đhsp", "dhsphn", "sphn", "hnue", "sph", "su pham ha noi"],
  },
  {
    id: "huce", slug: "truong-dai-hoc-xay-dung-ha-noi", code: "XDA", name: "Trường Đại học Xây dựng Hà Nội", shortName: "ĐH Xây dựng Hà Nội",
    type: "cong-lap", level: "dai-hoc", region: "bac", city: "Hà Nội", founded: 1966, students: 20000, highlight: "Cái nôi Kiến trúc, Xây dựng & Kết cấu công trình",
    campuses: ["55 Giải Phóng, Đồng Tâm, Hai Bà Trưng, Hà Nội"], website: "https://huce.edu.vn",
    description: "Đầu ngành về đào tạo Kỹ sư Xây dựng dân dụng, Cầu đường, Kiến trúc sư, Kỹ thuật môi trường và Quản lý đô thị.",
    scholarships: "Học bổng khuyến khích học tập và tài trợ từ các tập đoàn xây dựng hàng đầu (Coteccons, Hòa Bình, Vinaconex).",
    aliases: ["dhxd", "đhxd", "xdhn", "huce", "xda", "xay dung ha noi"],
  },
  {
    id: "hau", slug: "truong-dai-hoc-kien-truc-ha-noi", code: "KTA", name: "Trường Đại học Kiến trúc Hà Nội", shortName: "ĐH Kiến trúc Hà Nội",
    type: "cong-lap", level: "dai-hoc", region: "bac", city: "Hà Nội", founded: 1969, students: 14000, highlight: "Trung tâm đào tạo Kiến trúc, Quy hoạch & Mỹ thuật ứng dụng hàng đầu",
    campuses: ["Km 10 Đường Nguyễn Trãi, Thanh Xuân, Hà Nội"], website: "https://hau.edu.vn",
    description: "Cái nôi đào tạo Kiến trúc sư, Thiết kế nội thất, Thiết kế đồ họa, Quy hoạch đô thị và Kỹ thuật xây dựng công trình ngầm.",
    scholarships: "Học bổng từ các hội kiến trúc sư quốc tế và doanh nghiệp xây dựng.",
    aliases: ["dhkt", "đhkt", "kthn", "hau", "kta", "kien truc ha noi"],
  },
  {
    id: "utc", slug: "truong-dai-hoc-giao-thong-van-tai", code: "GHA", name: "Trường Đại học Giao thông Vận tải", shortName: "ĐH Giao thông Vận tải",
    type: "cong-lap", level: "dai-hoc", region: "bac", city: "Hà Nội", founded: 1960, students: 26000, highlight: "Trọng điểm Quốc gia về Hạ tầng giao thông, Ô tô & Logistics",
    campuses: ["Số 3 Cầu Giấy, Láng Thượng, Đống Đa, Hà Nội", "Phân hiệu TP.HCM: 450-451 Lê Văn Việt, Tăng Nhơn Phú A, TP. Thủ Đức"], website: "https://utc.edu.vn",
    description: "Đào tạo kỹ sư hạ tầng giao thông đường bộ, đường sắt đô thị, công nghệ ô tô, kỹ thuật điều khiển tự động và logistics.",
    scholarships: "Học bổng khuyến khích và tài trợ từ Bộ GTVT, các tổng công ty đường sắt, hàng hải.",
    aliases: ["dhgtvt", "đhgtvt", "gtvt", "utc", "gha", "giao thong van tai"],
  },
  {
    id: "ptit", slug: "hoc-vien-cong-nghe-buu-chinh-vien-thong", code: "BVH", name: "Học viện Công nghệ Bưu chính Viễn thông", shortName: "HV Bưu chính Viễn thông",
    type: "cong-lap", level: "hoc-vien", region: "bac", city: "Hà Nội", founded: 1997, students: 25000, highlight: "Top 1 Công nghệ Viễn thông, An toàn thông tin & Đa phương tiện",
    campuses: ["Km10 Đường Nguyễn Trãi, Hà Đông, Hà Nội", "Cơ sở TP.HCM: 11 Nguyễn Đình Chiểu, Đa Kao, Quận 1, TP.HCM"], website: "https://ptit.edu.vn",
    description: "Đơn vị đào tạo nòng cốt của Bộ TT&TT về Công nghệ thông tin, Viễn thông số, An toàn mạng, Thiết kế đồ họa và Thương mại điện tử.",
    scholarships: "Học bổng tài năng toàn phần, học bổng viện trợ từ Viettel, VNPT, MobiFone.",
    aliases: ["ptit", "bvh", "bcvs", "buu chinh", "hoc vien buu chinh", "ptit hn", "ptit hcm"],
  },
  {
    id: "aof", slug: "hoc-vien-tai-chinh", code: "HTC", name: "Học viện Tài chính", shortName: "Học viện Tài chính",
    type: "cong-lap", level: "hoc-vien", region: "bac", city: "Hà Nội", founded: 1963, students: 22000, highlight: "Cái nôi Tài chính, Kế toán & Thuế hàng đầu Việt Nam",
    campuses: ["Số 58 Lê Văn Hiến, Đức Thắng, Bắc Từ Liêm, Hà Nội"], website: "https://hvtc.edu.vn",
    description: "Trường đại học công lập trực thuộc Bộ Tài chính; cơ sở uy tín hàng đầu về đào tạo chuyên gia Tài chính công, Kế toán, Kiểm toán, Thuế và Hải quan.",
    scholarships: "Học bổng khuyến khích học tập, học bổng từ các hiệp hội nghề nghiệp quốc tế (ACCA, CPA, ICAEW).",
    aliases: ["hvtc", "htc", "aof", "tai chinh", "hoc vien tai chinh", "hv tai chinh"],
  },
  {
    id: "bav", slug: "hoc-vien-ngan-hang", code: "NHH", name: "Học viện Ngân hàng", shortName: "Học viện Ngân hàng",
    type: "cong-lap", level: "hoc-vien", region: "bac", city: "Hà Nội", founded: 1961, students: 23000, highlight: "Hàng đầu về Ngân hàng, Fintech & Tài chính ứng dụng",
    campuses: ["12 Chùa Bộc, Quang Trung, Đống Đa, Hà Nội", "Phân hiệu Bắc Ninh & Phú Yên"], website: "https://hvnh.edu.vn",
    description: "Trực thuộc Ngân hàng Nhà nước Việt Nam; trường đầu ngành về Tài chính - Ngân hàng, Công nghệ tài chính (Fintech), Kế toán và Kinh doanh quốc tế.",
    scholarships: "Học bổng Thống đốc Ngân hàng Nhà nước, học bổng các ngân hàng thương mại (Vietcombank, BIDV, Agribank, VietinBank).",
    aliases: ["hvnh", "nhh", "bav", "ngan hang", "hoc vien ngan hang", "hv ngan hang"],
  },
  {
    id: "dav", slug: "hoc-vien-ngoai-giao", code: "HQT", name: "Học viện Ngoại giao", shortName: "Học viện Ngoại giao",
    type: "cong-lap", level: "hoc-vien", region: "bac", city: "Hà Nội", founded: 1959, students: 6000, highlight: "Cái nôi Ngoại giao, Quan hệ quốc tế & Luật quốc tế",
    campuses: ["69 Chùa Láng, Láng Thượng, Đống Đa, Hà Nội"], website: "https://dav.edu.vn",
    description: "Trực thuộc Bộ Ngoại giao; trường đào tạo tinh hoa về Quan hệ quốc tế, Ngoại giao, Luật quốc tế, Truyền thông quốc tế và Kinh tế quốc tế.",
    scholarships: "Học bổng khuyến khích học tập, học bổng từ các đại sứ quán và tổ chức quốc tế.",
    aliases: ["hvng", "dav", "hqt", "ngoai giao", "hoc vien ngoai giao"],
  },
  {
    id: "ajc", slug: "hoc-vien-bao-chi-va-tuyen-truyen", code: "HBT", name: "Học viện Báo chí và Tuyên truyền", shortName: "Học viện Báo chí",
    type: "cong-lap", level: "hoc-vien", region: "bac", city: "Hà Nội", founded: 1962, students: 10000, highlight: "Cái nôi Báo chí, Truyền thông & Quan hệ công chúng",
    campuses: ["36 Xuân Thủy, Dịch Vọng Hậu, Cầu Giấy, Hà Nội"], website: "https://ajc.edu.vn",
    description: "Trường đại học trọng điểm về đào tạo Nhà báo, Biên tập viên, Chuyên viên Quan hệ công chúng (PR), Quảng cáo và Truyền thông đa phương tiện.",
    scholarships: "Học bổng khuyến khích học tập và học bổng từ các cơ quan báo chí, đài truyền hình VTV, VOV.",
    aliases: ["hvbctt", "ajc", "hbt", "hoc vien bao chi", "hv bao chi", "tuyen truyen"],
  },
  {
    id: "vnua", slug: "hoc-vien-nong-nghiep-viet-nam", code: "HVN", name: "Học viện Nông nghiệp Việt Nam", shortName: "Học viện Nông nghiệp",
    type: "cong-lap", level: "hoc-vien", region: "bac", city: "Hà Nội", founded: 1956, students: 28000, highlight: "Trọng điểm quốc gia về Nông nghiệp & Thực phẩm",
    campuses: ["Trâu Quỳ, Gia Lâm, Hà Nội"], website: "https://vnua.edu.vn",
    description: "Đào tạo đa ngành hàng đầu về Công nghệ thực phẩm, Khoa học môi trường, Bác sĩ thú y, Nông nghiệp công nghệ cao, Kinh tế nông nghiệp và CNSH.",
    scholarships: "Học bổng khuyến khích học tập, Quỹ học bổng thắp sáng ước mơ và tài trợ từ các tập đoàn nông nghiệp.",
    aliases: ["hvn", "vnua", "hvnongnghiep", "hoc vien nong nghiep", "nong nghiep 1", "nong nghiep ha noi"],
  },
  {
    id: "hlu", slug: "truong-dai-hoc-luat-ha-noi", code: "LPH", name: "Trường Đại học Luật Hà Nội", shortName: "ĐH Luật Hà Nội",
    type: "cong-lap", level: "dai-hoc", region: "bac", city: "Hà Nội", founded: 1979, students: 15000, highlight: "Trường đào tạo Pháp luật số 1 miền Bắc",
    campuses: ["87 Nguyễn Chí Thanh, Láng Thượng, Đống Đa, Hà Nội", "Phân hiệu Đắk Lắk: TP. Buôn Ma Thuột"], website: "https://hlu.edu.vn",
    description: "Trực thuộc Bộ Tư pháp; cơ sở đào tạo cán bộ pháp luật lớn nhất Việt Nam: Luật Dân sự, Hình sự, Luật Kinh tế, Luật Thương mại quốc tế.",
    scholarships: "Học bổng khuyến khích học tập và học bổng từ các hãng luật danh tiếng.",
    aliases: ["dhlhn", "đhlhn", "lhn", "hlu", "lph", "luat ha noi", "dh luat ha noi"],
  },
  {
    id: "tmu", slug: "truong-dai-hoc-thuong-mai", code: "TMA", name: "Trường Đại học Thương mại", shortName: "ĐH Thương mại",
    type: "cong-lap", level: "dai-hoc", region: "bac", city: "Hà Nội", founded: 1960, students: 20000, highlight: "Top 1 Thương mại điện tử, Marketing & Logistics",
    campuses: ["79 Hồ Tùng Mậu, Mai Dịch, Cầu Giấy, Hà Nội", "Cơ sở Hà Nam: Đường Lý Thường Kiệt, TP. Phủ Lý"], website: "https://tmu.edu.vn",
    description: "Thế mạnh vượt trội về Thương mại điện tử, Quản trị chuỗi cung ứng, Marketing, Kinh doanh quốc tế và Kế toán doanh nghiệp.",
    scholarships: "Học bổng khuyến khích học tập, học bổng hỗ trợ sinh viên vượt khó và học bổng doanh nghiệp.",
    aliases: ["dhtm", "đhtm", "tmu", "tma", "thuong mai", "dai hoc thuong mai"],
  },
  {
    id: "haui", slug: "truong-dai-hoc-cong-nghiep-ha-noi", code: "DCN", name: "Trường Đại học Công nghiệp Hà Nội", shortName: "ĐH Công nghiệp Hà Nội",
    type: "cong-lap", level: "dai-hoc", region: "bac", city: "Hà Nội", founded: 1898, students: 32000, highlight: "Trường kỹ thuật ứng dụng quy mô lớn nhất",
    campuses: ["Số 298 đường Cầu Diễn, Bắc Từ Liêm, Hà Nội", "Cơ sở 2: Tây Tựu, Bắc Từ Liêm, Hà Nội", "Cơ sở 3: Phù Cừ, Hưng Yên"], website: "https://haui.edu.vn",
    description: "Trường kỹ thuật định hướng ứng dụng thực hành cao: Cơ khí, Ô tô, Điện - Điện tử, Tự động hóa, CNTT và May mặc thời trang.",
    scholarships: "Học bổng tài trợ của doanh nghiệp Nhật Bản, Hàn Quốc và học bổng khuyến khích.",
    aliases: ["dhcnhn", "đhcnhn", "cnhn", "haui", "dcn", "cong nghiep ha noi"],
  },
  {
    id: "fpt", slug: "truong-dai-hoc-fpt", code: "FPT", name: "Trường Đại học FPT", shortName: "ĐH FPT",
    type: "tu-thuc", level: "dai-hoc", region: "bac", city: "Hà Nội", founded: 2006, students: 30000, highlight: "100% sinh viên thực tập On-the-Job Training",
    campuses: ["Khu CNC Hòa Lạc, Thạch Thất, Hà Nội", "Cơ sở TP.HCM, Đà Nẵng, Cần Thơ, Quy Nhơn"], website: "https://fpt.edu.vn",
    description: "Thuộc Tập đoàn FPT; tiên phong đào tạo CNTT, Kỹ thuật phần mềm, AI, Thiết kế đồ họa, Quản trị kinh doanh và Ngôn ngữ.",
    scholarships: "Học bổng Nguyễn Văn Đạo từ 30% - 100% toàn khóa học cho học sinh giỏi.",
    aliases: ["dhfpt", "đhfpt", "fpt", "fptu", "dai hoc fpt"],
  },
  {
    id: "phenikaa", slug: "truong-dai-hoc-phenikaa", code: "PKA", name: "Trường Đại học Phenikaa", shortName: "ĐH Phenikaa",
    type: "tu-thuc", level: "dai-hoc", region: "bac", city: "Hà Nội", founded: 2007, students: 16000, highlight: "Đại học đổi mới sáng tạo, cơ sở vật chất 5 sao",
    campuses: ["Đường Nguyễn Văn Trác, Yên Nghĩa, Hà Đông, Hà Nội"], website: "https://phenikaa-uni.edu.vn",
    description: "Đại học đa ngành phi lợi nhuận thuộc Tập đoàn Phenikaa, đầu tư mạnh về Vi mạch bán dẫn, Kỹ thuật y sinh, Dược và Khoa học máy tính.",
    scholarships: "Quỹ học bổng Phenikaa 50 tỷ đồng/năm (Học bổng Chủ tịch, Học bổng Tài năng).",
    aliases: ["pka", "phenikaa", "dh phenikaa", "đh phenikaa"],
  },
  {
    id: "vinuni", slug: "truong-dai-hoc-vinuni", code: "VIN", name: "Trường Đại học VinUniversity", shortName: "VinUni",
    type: "tu-thuc", level: "dai-hoc", region: "bac", city: "Hà Nội", founded: 2019, students: 2000, highlight: "Đại học tinh hoa chuẩn quốc tế hợp tác Cornell & UPenn",
    campuses: ["Khu đô thị Vinhomes Ocean Park, Gia Lâm, Hà Nội"], website: "https://vinuni.edu.vn",
    description: "Đại học phi lợi nhuận đẳng cấp quốc tế của Tập đoàn Vingroup, đào tạo Quản trị kinh doanh, Kỹ thuật - KHMT và Y khoa.",
    scholarships: "100% sinh viên được tài trợ 35% học phí; học bổng tài năng toàn phần 100% + sinh hoạt phí.",
    aliases: ["vinuni", "vin", "dai hoc vinuni", "vin university"],
  },
  {
    id: "cd-fpt-hn", slug: "truong-cao-dang-fpt-polytechnic-ha-noi", code: "CD-FPT", name: "Trường Cao đẳng FPT Polytechnic Hà Nội", shortName: "CĐ FPT Polytechnic Hà Nội",
    type: "tu-thuc", level: "cao-dang", region: "bac", city: "Hà Nội", founded: 2010, students: 18000, highlight: "Thực học – Thực nghiệp, 97.7% sinh viên có việc làm sau tốt nghiệp",
    campuses: ["Tòa nhà FPT Polytechnic, Phố Trịnh Văn Bô, Nam Từ Liêm, Hà Nội"], website: "https://caodang.fpt.edu.vn",
    description: "Trường cao đẳng thực hành số 1 về CNTT (Lập trình Web/Mobile), Thiết kế đồ họa, Digital Marketing, Thương mại điện tử và Tự động hóa.",
    scholarships: "Học bổng khuyến học FPT Polytechnic, ưu đãi tân sinh viên nhập học sớm.",
    aliases: ["cd fpt", "cđ fpt", "fpt poly", "polytechnic", "cd-fpt", "cao dang fpt"],
  },
  {
    id: "cd-dlhn", slug: "truong-cao-dang-du-lich-ha-noi", code: "CD-DLHN", name: "Trường Cao đẳng Du lịch Hà Nội", shortName: "CĐ Du lịch Hà Nội",
    type: "cong-lap", level: "cao-dang", region: "bac", city: "Hà Nội", founded: 1972, students: 6000, highlight: "Cái nôi đào tạo nghề Du lịch, Khách sạn & Ẩm thực số 1",
    campuses: ["236 Hoàng Quốc Việt, Cổ Nhuế 1, Bắc Từ Liêm, Hà Nội"], website: "https://htc.edu.vn",
    description: "Trực thuộc Bộ VHTTDL; cơ sở đào tạo nghề Quản trị khách sạn, Hướng dẫn du lịch, Kỹ thuật chế biến món ăn uy tín hàng đầu.",
    scholarships: "Học bổng khuyến khích nghề nghiệp, học bổng từ các tập đoàn khách sạn 5 sao.",
    aliases: ["cddl", "cđdl", "cd du lich", "cđ du lich", "cd-dlhn", "cao dang du lich ha noi"],
  },
  {
    id: "cd-hht", slug: "truong-cao-dang-cong-nghe-cao-ha-noi", code: "CD-HHT", name: "Trường Cao đẳng Công nghệ cao Hà Nội", shortName: "CĐ Công nghệ cao Hà Nội",
    type: "cong-lap", level: "cao-dang", region: "bac", city: "Hà Nội", founded: 2009, students: 8000, highlight: "Trường Cao đẳng nghề chất lượng cao chuẩn quốc tế",
    campuses: ["Phường Tây Mỗ, Quận Nam Từ Liêm, Hà Nội"], website: "https://hht.edu.vn",
    description: "Đào tạo nghề chất lượng cao chuẩn Đức và ASEAN: Cơ điện tử, Công nghệ ô tô, Điện tử công nghiệp, CNTT và Chăm sóc sắc đẹp.",
    scholarships: "Học bổng chính phủ, học bổng đào tạo chuyển giao nghề chuẩn quốc tế.",
    aliases: ["cdcnc", "cđcnc", "cd hht", "hht", "cd-hht", "cao dang cong nghe cao"],
  },
  {
    id: "cd-yhn", slug: "truong-cao-dang-y-te-ha-noi", code: "CD-YHN", name: "Trường Cao đẳng Y tế Hà Nội", shortName: "CĐ Y tế Hà Nội",
    type: "cong-lap", level: "cao-dang", region: "bac", city: "Hà Nội", founded: 1966, students: 5000, highlight: "Trường Cao đẳng đào tạo Cử nhân Điều dưỡng, Dược & Xét nghiệm y học",
    campuses: ["35 Đoàn Thị Điểm, Quốc Tử Giám, Đống Đa, Hà Nội"], website: "https://yhn.edu.vn",
    description: "Đào tạo điều dưỡng viên, dược sĩ cao đẳng và kỹ thuật viên xét nghiệm y học chất lượng cao cho hệ thống y tế.",
    scholarships: "Học bổng khuyến khích ngành nghề sức khỏe và hỗ trợ thực tập bệnh viện.",
    aliases: ["cd yhn", "cd y te ha noi", "cđ y te ha noi"],
  },

  // ── MIỀN TRUNG & TÂY NGUYÊN ───────────────────────────────────────────────
  {
    id: "dut", slug: "truong-dai-hoc-bach-khoa-dh-da-nang", code: "DDK", name: "Trường ĐH Bách khoa – ĐH Đà Nẵng", shortName: "ĐH Bách khoa – ĐH Đà Nẵng",
    type: "cong-lap", level: "dai-hoc", region: "trung", city: "Đà Nẵng", founded: 1975, students: 18000, highlight: "Top 1 Kỹ thuật & Công nghệ miền Trung",
    campuses: ["54 Nguyễn Lương Bằng, Liên Chiểu, Đà Nẵng"], website: "https://dut.udn.vn",
    description: "Trường kỹ thuật lớn nhất miền Trung: CNTT, Kỹ thuật phần mềm, Cơ điện tử, Ô tô, Tự động hóa, Xây dựng và Kiến trúc.",
    scholarships: "Học bổng khuyến khích học tập và tài trợ từ các tập đoàn kỹ thuật (Murata, Mabuchi Motor, Bosch).",
    aliases: ["bkdn", "bk da nang", "dut", "ddk", "bach khoa da nang"],
  },
  {
    id: "due", slug: "truong-dai-hoc-kinh-te-dh-da-nang", code: "DDQ", name: "Trường ĐH Kinh tế – ĐH Đà Nẵng", shortName: "ĐH Kinh tế – ĐH Đà Nẵng",
    type: "cong-lap", level: "dai-hoc", region: "trung", city: "Đà Nẵng", founded: 1975, students: 16000, highlight: "Top 1 Kinh tế & Quản trị kinh doanh miền Trung",
    campuses: ["71 Ngũ Hành Sơn, Bắc Mỹ An, Ngũ Hành Sơn, Đà Nẵng"], website: "https://due.udn.vn",
    description: "Đào tạo chuyên gia kinh tế, kinh doanh quốc tế, marketing, thương mại điện tử, tài chính ngân hàng và du lịch.",
    scholarships: "Học bổng khuyến khích ĐH Đà Nẵng, học bổng từ các ngân hàng thương mại.",
    aliases: ["ktdn", "due", "ddq", "kinh te da nang"],
  },
  {
    id: "vku", slug: "truong-dai-hoc-cntt-va-truyen-thong-viet-han", code: "VKU", name: "Trường ĐH CNTT và Truyền thông Việt - Hàn", shortName: "ĐH Việt - Hàn (VKU)",
    type: "cong-lap", level: "dai-hoc", region: "trung", city: "Đà Nẵng", founded: 2020, students: 7000, highlight: "Hợp tác chính phủ Việt Nam - Hàn Quốc (KOICA)",
    campuses: ["470 Đường Trần Đại Nghĩa, Hòa Quý, Ngũ Hành Sơn, Đà Nẵng"], website: "https://vku.udn.vn",
    description: "Thế mạnh về Công nghệ thông tin, Trí tuệ nhân tạo, Vi mạch bán dẫn, An toàn thông tin và Thiết kế mỹ thuật số.",
    scholarships: "Học bổng KOICA và học bổng doanh nghiệp công nghệ Hàn Quốc.",
    aliases: ["vku", "viet han", "cntt viet han", "dh viet han"],
  },
  {
    id: "hump", slug: "truong-dai-hoc-y-duoc-dh-hue", code: "DHY", name: "Trường Đại học Y Dược – ĐH Huế", shortName: "ĐH Y Dược – ĐH Huế",
    type: "cong-lap", level: "dai-hoc", region: "trung", city: "Huế", founded: 1957, students: 11000, highlight: "Trường Y Dược trọng điểm miền Trung - Tây Nguyên",
    campuses: ["06 Ngô Quyền, Vĩnh Ninh, TP. Huế"], website: "https://huemed-univ.edu.vn",
    description: "Đào tạo Bác sĩ Y đa khoa, Răng - Hàm - Mặt, Y học cổ truyền, Dược sĩ, Điều dưỡng và Kỹ thuật y học uy tín bậc nhất miền Trung.",
    scholarships: "Học bổng khuyến khích học tập và học bổng từ các tổ chức y tế quốc tế.",
    aliases: ["dhyh", "hump", "dhy", "y hue", "y duoc hue"],
  },
  {
    id: "dtu", slug: "truong-dai-hoc-duy-tan", code: "DDT", name: "Trường Đại học Duy Tân", shortName: "ĐH Duy Tân",
    type: "tu-thuc", level: "dai-hoc", region: "trung", city: "Đà Nẵng", founded: 1994, students: 22000, highlight: "Top 500 Đại học Thế giới (THE & QS Rankings)",
    campuses: ["254 Nguyễn Văn Linh, Thanh Khê, Đà Nẵng", "Khu Đô thị Nam Kỳ Khởi Nghĩa, Hòa Hải, Ngũ Hành Sơn, Đà Nẵng"], website: "https://duytan.edu.vn",
    description: "Đại học tư thục hàng đầu miền Trung đạt chuẩn kiểm định ABET (Mỹ) về CNTT và Kỹ thuật; đào tạo đa ngành từ Y Dược, Kỹ thuật đến Du lịch.",
    scholarships: "Học bổng toàn phần, học bổng tài năng từ 50% - 100% học phí toàn khóa.",
    aliases: ["dtu", "ddt", "duy tan", "dh duy tan"],
  },
  {
    id: "cd-dldn", slug: "truong-cao-dang-du-lich-da-nang", code: "CD-DLDN", name: "Trường Cao đẳng Du lịch Đà Nẵng", shortName: "CĐ Du lịch Đà Nẵng",
    type: "cong-lap", level: "cao-dang", region: "trung", city: "Đà Nẵng", founded: 2008, students: 4000, highlight: "Trường Cao đẳng thực hành du lịch hàng đầu miền Trung",
    campuses: ["Đường Nam Kỳ Khởi Nghĩa, Tổ 69, Phường Hòa Hải, Ngũ Hành Sơn, Đà Nẵng"], website: "https://dvtc.edu.vn",
    description: "Đào tạo thực hành nghề Lữ hành, Khách sạn, Nhà hàng, Hướng dẫn viên du lịch và Kỹ thuật làm bánh ẩm thực.",
    scholarships: "Học bổng khuyến khích học nghề và liên kết việc làm tại resort 5 sao Đà Nẵng, Hội An.",
    aliases: ["cd dldn", "cd du lich da nang", "cđ du lich da nang"],
  },

  // ── MIỀN NAM & TP. HỒ CHÍ MINH ─────────────────────────────────────────────
  {
    id: "hcmut", slug: "truong-dai-hoc-bach-khoa-dhqg-tphcm", code: "QSB", name: "Trường ĐH Bách khoa – ĐHQG TP.HCM", shortName: "ĐH Bách khoa – ĐHQG TP.HCM",
    type: "cong-lap", level: "dai-hoc", region: "nam", city: "TP. Hồ Chí Minh", founded: 1957, students: 26000, highlight: "Top 1 Kỹ thuật & Công nghệ miền Nam",
    campuses: ["268 Lý Thường Kiệt, Phường 14, Quận 10, TP.HCM", "Cơ sở Dĩ An: Khu đô thị ĐHQG TP.HCM, Dĩ An, Bình Dương"], website: "https://hcmut.edu.vn",
    description: "Trường đại học kỹ thuật hàng đầu phía Nam; đạt chuẩn kiểm định ABET (Mỹ) về Khoa học máy tính và Kỹ thuật máy tính.",
    scholarships: "Học bổng khuyến khích, Quỹ học bổng cựu sinh viên Phú Thọ - Bách Khoa và các tập đoàn công nghệ toàn cầu.",
    aliases: ["dhbk tphcm", "bktphcm", "hcmut", "qsb", "bach khoa tphcm", "bach khoa hcm"],
  },
  {
    id: "hcmus", slug: "truong-dai-hoc-khoa-hoc-tu-nhien-dhqg-tphcm", code: "QST", name: "Trường ĐH Khoa học Tự nhiên – ĐHQG TP.HCM", shortName: "ĐH Khoa học Tự nhiên – ĐHQG TP.HCM",
    type: "cong-lap", level: "dai-hoc", region: "nam", city: "TP. Hồ Chí Minh", founded: 1941, students: 18000, highlight: "Đầu ngành Khoa học máy tính, AI & Khoa học cơ bản miền Nam",
    campuses: ["227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP.HCM", "Cơ sở Thủ Đức: Khu đô thị ĐHQG TP.HCM, TP. Thủ Đức"], website: "https://hcmus.edu.vn",
    description: "Cái nôi đào tạo chuyên gia Công nghệ thông tin, Trí tuệ nhân tạo, Khoa học dữ liệu, Công nghệ sinh học và Hóa học hàng đầu.",
    scholarships: "Học bổng Khuyến khích học tập, Quỹ ươm mầm tài năng khoa học tự nhiên.",
    aliases: ["khtn tphcm", "hcmus", "qst", "khoa hoc tu nhien hcm"],
  },
  {
    id: "ussh-hcm", slug: "truong-dai-hoc-khxhnv-dhqg-tphcm", code: "QSX", name: "Trường ĐH Khoa học Xã hội và Nhân văn – ĐHQG TP.HCM", shortName: "ĐH KHXH&NV – ĐHQG TP.HCM",
    type: "cong-lap", level: "dai-hoc", region: "nam", city: "TP. Hồ Chí Minh", founded: 1957, students: 16000, highlight: "Đầu ngành Khoa học Xã hội & Ngôn ngữ miền Nam",
    campuses: ["10-12 Đinh Tiên Hoàng, Bến Nghé, Quận 1, TP.HCM", "Cơ sở Thủ Đức: Khu đô thị ĐHQG TP.HCM, TP. Thủ Đức"], website: "https://hcmussh.edu.vn",
    description: "Đào tạo tinh hoa về Báo chí & Truyền thông, Quan hệ quốc tế, Tâm lý học, Du lịch, Ngôn ngữ Anh và các thứ tiếng.",
    scholarships: "Học bổng khuyến khích ĐHQG TP.HCM và học bổng từ các lãnh sự quán quốc tế.",
    aliases: ["dhxhnv tphcm", "ussh hcm", "qsx", "nhan van tphcm"],
  },
  {
    id: "uit", slug: "truong-dai-hoc-cong-nghe-thong-tin-dhqg-tphcm", code: "QSC", name: "Trường ĐH Công nghệ Thông tin – ĐHQG TP.HCM", shortName: "ĐH Công nghệ Thông tin – ĐHQG TP.HCM",
    type: "cong-lap", level: "dai-hoc", region: "nam", city: "TP. Hồ Chí Minh", founded: 2006, students: 9000, highlight: "Trường chuyên sâu CNTT, An toàn thông tin & AI số 1",
    campuses: ["Khu phố 6, P. Linh Trung, TP. Thủ Đức, TP.HCM"], website: "https://uit.edu.vn",
    description: "Trường đại học chuyên ngành CNTT và Truyền thông hàng đầu; đào tạo chuyên sâu Khoa học máy tính, Kỹ thuật phần mềm, An toàn thông tin và Vi mạch.",
    scholarships: "Học bổng tuyển sinh tài năng, học bổng doanh nghiệp (VNG, FPT Software, TMA Solutions).",
    aliases: ["uit", "qsc", "cntt dhqg", "dh cong nghe thong tin"],
  },
  {
    id: "uel", slug: "truong-dai-hoc-kinh-te-luat-dhqg-tphcm", code: "QSK", name: "Trường ĐH Kinh tế – Luật – ĐHQG TP.HCM", shortName: "ĐH Kinh tế – Luật – ĐHQG TP.HCM",
    type: "cong-lap", level: "dai-hoc", region: "nam", city: "TP. Hồ Chí Minh", founded: 2000, students: 12000, highlight: "Giao thoa đỉnh cao giữa Kinh tế & Pháp luật",
    campuses: ["669 Quốc lộ 1, Khu phố 3, P. Linh Xuân, TP. Thủ Đức, TP.HCM"], website: "https://uel.edu.vn",
    description: "Đào tạo các chuyên ngành mũi nhọn: Kinh tế đối ngoại, Luật thương mại quốc tế, Fintech, Thương mại điện tử và Kiểm toán.",
    scholarships: "Học bổng tài năng UEL, học bổng từ các ngân hàng và hãng luật lớn.",
    aliases: ["uel", "qsk", "kinh te luat", "dh kinh te luat"],
  },
  {
    id: "iu", slug: "truong-dai-hoc-quoc-te-dhqg-tphcm", code: "QSG", name: "Trường ĐH Quốc tế – ĐHQG TP.HCM", shortName: "ĐH Quốc tế – ĐHQG TP.HCM",
    type: "cong-lap", level: "dai-hoc", region: "nam", city: "TP. Hồ Chí Minh", founded: 2003, students: 9000, highlight: "100% giảng dạy bằng tiếng Anh, chuẩn ABET & AUN-QA",
    campuses: ["Khu phố 6, P. Linh Trung, TP. Thủ Đức, TP.HCM"], website: "https://hcmiu.edu.vn",
    description: "Đại học công lập đầu tiên giảng dạy hoàn toàn bằng tiếng Anh: Kỹ thuật Y sinh, Logistics, Khoa học dữ liệu, Quản trị kinh doanh và CNSH.",
    scholarships: "Học bổng toàn phần 100% học phí và bán phần 50% cho học sinh xuất sắc.",
    aliases: ["hcmiu", "iu", "qsg", "dai hoc quoc te"],
  },
  {
    id: "ueh", slug: "dai-hoc-kinh-te-tp-ho-chi-minh", code: "KSA", name: "Đại học Kinh tế TP. Hồ Chí Minh", shortName: "ĐH Kinh tế TP.HCM",
    type: "cong-lap", level: "dai-hoc", region: "nam", city: "TP. Hồ Chí Minh", founded: 1976, students: 32000, highlight: "Top 1 Đại học Kinh tế & Kinh doanh miền Nam",
    campuses: ["59C Nguyễn Đình Chiểu, Phường 6, Quận 3, TP.HCM", "Cơ sở B: 279 Nguyễn Tri Phương, Quận 10, TP.HCM", "Phân hiệu Vĩnh Long: 1B Nguyễn Trung Trực, TP. Vĩnh Long"], website: "https://ueh.edu.vn",
    description: "Trường đại học đa ngành hàng đầu về kinh tế, quản trị, tài chính, logistics, công nghệ tài chính, luật kinh tế và thiết kế truyền thông.",
    scholarships: "Học bổng tuyển sinh xuất sắc, học bổng khuyến khích và tài trợ từ hơn 100 doanh nghiệp đối tác.",
    aliases: ["ueh", "ksa", "kinh te tphcm", "dh kinh te tphcm"],
  },
  {
    id: "ump", slug: "truong-dai-hoc-y-duoc-tp-ho-chi-minh", code: "YDS", name: "Trường Đại học Y Dược TP. Hồ Chí Minh", shortName: "ĐH Y Dược TP.HCM",
    type: "cong-lap", level: "dai-hoc", region: "nam", city: "TP. Hồ Chí Minh", founded: 1947, students: 15000, highlight: "Trung tâm Y Dược học hàng đầu phía Nam",
    campuses: ["217 Hồng Bàng, Phường 11, Quận 5, TP.HCM"], website: "https://ump.edu.vn",
    description: "Cơ sở đào tạo y tế đầu ngành: Bác sĩ Y đa khoa, Bác sĩ Răng - Hàm - Mặt, Dược sĩ, Y học cổ truyền, Kỹ thuật y học và Điều dưỡng.",
    scholarships: "Học bổng khuyến khích và học bổng tài trợ sinh viên vượt khó từ các bệnh viện lớn.",
    aliases: ["ydshcm", "ump", "yds", "y duoc tphcm", "y duoc hcm"],
  },
  {
    id: "pntu", slug: "truong-dai-hoc-y-khoa-pham-ngoc-thach", code: "TYS", name: "Trường Đại học Y khoa Phạm Ngọc Thạch", shortName: "ĐH Y khoa Phạm Ngọc Thạch",
    type: "cong-lap", level: "dai-hoc", region: "nam", city: "TP. Hồ Chí Minh", founded: 1989, students: 10000, highlight: "Trường Y khoa trọng điểm trực thuộc UBND TP.HCM",
    campuses: ["Số 2 Dương Quang Trung, Phường 12, Quận 10, TP.HCM"], website: "https://pnt.edu.vn",
    description: "Đào tạo nhân lực y tế chất lượng cao: Y đa khoa, Răng - Hàm - Mặt, Dược học, Khúc xạ nhãn khoa, Kỹ thuật xét nghiệm y học.",
    scholarships: "Học bổng khuyến khích học tập và hỗ trợ học phí cho sinh viên xuất sắc.",
    aliases: ["pntu", "tys", "pham ngoc thach", "y pham ngoc thach"],
  },
  {
    id: "hcmute", slug: "truong-dai-hoc-su-pham-ky-thuat-tp-ho-chi-minh", code: "SPK", name: "Trường ĐH Sư phạm Kỹ thuật TP. Hồ Chí Minh", shortName: "ĐH Sư phạm Kỹ thuật TP.HCM",
    type: "cong-lap", level: "dai-hoc", region: "nam", city: "TP. Hồ Chí Minh", founded: 1962, students: 24000, highlight: "Cái nôi đào tạo Kỹ thuật & Công nghệ ứng dụng hàng đầu",
    campuses: ["01 Võ Văn Ngân, Linh Chiểu, TP. Thủ Đức, TP.HCM"], website: "https://hcmute.edu.vn",
    description: "Thế mạnh vượt trội về Kỹ thuật ô tô, Cơ điện tử, Tự động hóa, CNTT, Kỹ thuật robot, Công nghệ thực phẩm và Thiết kế thời trang.",
    scholarships: "Học bổng khuyến khích học tập và tài trợ từ các tập đoàn công nghệ (Intel, Siemens, Omron).",
    aliases: ["spkt", "spkt tphcm", "hcmute", "spk", "su pham ky thuat"],
  },
  {
    id: "hcmue", slug: "truong-dai-hoc-su-pham-tp-ho-chi-minh", code: "SPS", name: "Trường Đại học Sư phạm TP. Hồ Chí Minh", shortName: "ĐH Sư phạm TP.HCM",
    type: "cong-lap", level: "dai-hoc", region: "nam", city: "TP. Hồ Chí Minh", founded: 1976, students: 20000, highlight: "Trường Sư phạm trọng điểm quốc gia phía Nam",
    campuses: ["280 An Dương Vương, Phường 4, Quận 5, TP.HCM"], website: "https://hcmue.edu.vn",
    description: "Đào tạo giáo viên mẫu mực các môn tự nhiên, xã hội, ngoại ngữ, giáo dục tiểu học, mầm non và tâm lý giáo dục.",
    scholarships: "Trợ cấp sinh hoạt phí và miễn học phí theo Nghị định 116 của Chính phủ.",
    aliases: ["dhsp tphcm", "sps", "hcmue", "su pham tphcm"],
  },
  {
    id: "nlu", slug: "truong-dai-hoc-nong-lam-tp-ho-chi-minh", code: "NLS", name: "Trường Đại học Nông Lâm TP. Hồ Chí Minh", shortName: "ĐH Nông Lâm TP.HCM",
    type: "cong-lap", level: "dai-hoc", region: "nam", city: "TP. Hồ Chí Minh", founded: 1955, students: 22000, highlight: "Đầu ngành Nông Lâm nghiệp, Thú y, Chế biến thực phẩm & CNSH",
    campuses: ["Khu phố 6, Phường Linh Trung, TP. Thủ Đức, TP.HCM", "Phân hiệu Gia Lai & Ninh Thuận"], website: "https://hcmuaf.edu.vn",
    description: "Đào tạo Bác sĩ Thú y, Kỹ sư Nông nghiệp công nghệ cao, Công nghệ thực phẩm, Khoa học môi trường, Lâm nghiệp và Quản lý đất đai.",
    scholarships: "Học bổng tài trợ của các tập đoàn nông nghiệp đa quốc gia (C.P., Japfa, De Heus).",
    aliases: ["nlu", "nls", "nong lam tphcm", "dh nong lam"],
  },
  {
    id: "hcmulaw", slug: "truong-dai-hoc-luat-tp-ho-chi-minh", code: "LPS", name: "Trường Đại học Luật TP. Hồ Chí Minh", shortName: "ĐH Luật TP.HCM",
    type: "cong-lap", level: "dai-hoc", region: "nam", city: "TP. Hồ Chí Minh", founded: 1996, students: 14000, highlight: "Trường đại học đào tạo Luật lớn nhất miền Nam",
    campuses: ["Số 02 Nguyễn Tất Thành, Phường 12, Quận 4, TP.HCM", "Cơ sở 2: Số 123 Quốc lộ 13, Hiệp Bình Chánh, TP. Thủ Đức"], website: "https://hcmulaw.edu.vn",
    description: "Trực thuộc Bộ Giáo dục & Đào tạo; đào tạo chuyên sâu Luật Dân sự, Luật Hình sự, Luật Thương mại quốc tế, Quản trị - Luật.",
    scholarships: "Học bổng khuyến khích và học bổng từ các công ty luật đa quốc gia.",
    aliases: ["dhluat tphcm", "hcmulaw", "ulaw", "lps", "luat tphcm", "dh luat tphcm"],
  },
  {
    id: "tdtu", slug: "truong-dai-hoc-ton-duc-thang", code: "DTT", name: "Trường Đại học Tôn Đức Thắng", shortName: "ĐH Tôn Đức Thắng",
    type: "cong-lap", level: "dai-hoc", region: "nam", city: "TP. Hồ Chí Minh", founded: 1997, students: 26000, highlight: "Đại học chuẩn quốc tế QS 5 sao, tự chủ tài chính tiên phong",
    campuses: ["19 Nguyễn Hữu Thọ, Tân Phong, Quận 7, TP.HCM", "Cơ sở Bảo Lộc, Nha Trang, Cà Mau"], website: "https://tdtu.edu.vn",
    description: "Cơ sở vật chất hiện đại hàng đầu Việt Nam: đào tạo CNTT, Kỹ thuật phần mềm, Quản trị kinh doanh, Thiết kế đồ họa, Luật và Dược.",
    scholarships: "Quỹ học bổng tài năng toàn phần 100% học phí cho học sinh trường chuyên và thành tích cao.",
    aliases: ["tdtu", "dtt", "ton duc thang", "dh ton duc thang"],
  },
  {
    id: "iuh", slug: "truong-dai-hoc-cong-nghiep-tp-ho-chi-minh", code: "HUI", name: "Trường Đại học Công nghiệp TP. Hồ Chí Minh", shortName: "ĐH Công nghiệp TP.HCM",
    type: "cong-lap", level: "dai-hoc", region: "nam", city: "TP. Hồ Chí Minh", founded: 1956, students: 35000, highlight: "Trường đại học đạt chuẩn kiểm định Quốc tế ABET & AUN-QA",
    campuses: ["12 Nguyễn Văn Bảo, Phường 4, Gò Vấp, TP.HCM", "Phân hiệu Quảng Ngãi & Thanh Hóa"], website: "https://iuh.edu.vn",
    description: "Quy mô đào tạo lớn hàng đầu phía Nam: Kỹ thuật ô tô, Cơ khí, Tự động hóa, CNTT, Hóa học, Thực phẩm và Quản trị kinh doanh.",
    scholarships: "Quỹ học bổng 50 tỷ đồng/năm từ nhà trường và các doanh nghiệp FDI.",
    aliases: ["iuh", "hui", "cong nghiep tphcm", "dh cong nghiep tphcm"],
  },
  {
    id: "ctu", slug: "truong-dai-hoc-can-tho", code: "TCT", name: "Trường Đại học Cần Thơ", shortName: "ĐH Cần Thơ",
    type: "cong-lap", level: "dai-hoc", region: "nam", city: "Cần Thơ", founded: 1966, students: 45000, highlight: "Đại học trọng điểm quốc gia lớn nhất vùng Đồng bằng Sông Cửu Long",
    campuses: ["Khu II, Đường 3/2, Xuân Khánh, Ninh Kiều, Cần Thơ", "Khu I, Khu III, Khu Hòa An (Hậu Giang)"], website: "https://ctu.edu.vn",
    description: "Trung tâm đào tạo và nghiên cứu khoa học lớn nhất miền Tây: Nông nghiệp, Thủy sản, CNSH, CNTT, Sư phạm, Kinh tế và Kỹ thuật công nghệ.",
    scholarships: "Học bổng khuyến khích ĐH Cần Thơ, học bổng ODA Nhật Bản và các dự án quốc tế.",
    aliases: ["ctu", "tct", "dh can tho", "dai hoc can tho"],
  },
  {
    id: "rmit", slug: "truong-dai-hoc-rmit-viet-nam", code: "RMIT", name: "Trường Đại học RMIT Việt Nam", shortName: "RMIT Việt Nam",
    type: "quoc-te", level: "dai-hoc", region: "nam", city: "TP. Hồ Chí Minh", founded: 2000, students: 12000, highlight: "Đại học quốc tế danh tiếng của Úc tại Việt Nam",
    campuses: ["702 Nguyễn Văn Linh, Tân Phong, Quận 7, TP.HCM", "Cơ sở Hà Nội: 521 Kim Mã, Ba Đình, Hà Nội"], website: "https://rmit.edu.vn",
    description: "Bằng cấp quốc tế từ RMIT Melbourne: Kinh doanh, Marketing, Thiết kế đồ họa, Truyền thông số, Kỹ thuật phần mềm và AI.",
    scholarships: "Học bổng Hiệu trưởng toàn phần 100% và học bổng tài năng 50%-25%.",
    aliases: ["rmit", "rmit vn", "dai hoc rmit", "rmit vietnam"],
  },
  {
    id: "hutech", slug: "truong-dai-hoc-cong-nghe-tp-ho-chi-minh", code: "HUTECH", name: "Trường ĐH Công nghệ TP. Hồ Chí Minh (HUTECH)", shortName: "HUTECH",
    type: "tu-thuc", level: "dai-hoc", region: "nam", city: "TP. Hồ Chí Minh", founded: 1995, students: 35000, highlight: "Đại học năng động, thực học – thực nghiệp",
    campuses: ["475A Điện Biên Phủ, Phường 25, Bình Thạnh, TP.HCM", "Cơ sở Khu CNC TP. Thủ Đức"], website: "https://hutech.edu.vn",
    description: "Đào tạo đa ngành: Công nghệ kỹ thuật ô tô, Kỹ thuật phần mềm, Truyền thông đa phương tiện, Quản trị khách sạn, Dược học và Thanh nhạc.",
    scholarships: "Học bổng tài năng, học bổng tự hào HUTECH từ 25% - 100% học phí.",
    aliases: ["hutech", "dkc", "dh cong nghe tphcm", "dai hoc hutech"],
  },
  {
    id: "vlu-sg", slug: "truong-dai-hoc-van-lang", code: "VLU", name: "Trường Đại học Văn Lang", shortName: "ĐH Văn Lang",
    type: "tu-thuc", level: "dai-hoc", region: "nam", city: "TP. Hồ Chí Minh", founded: 1995, students: 30000, highlight: "Cơ sở vật chất hiện đại, thế mạnh Thiết kế, Nghệ thuật & Y Dược",
    campuses: ["69/68 Đặng Thùy Trâm, Phường 13, Bình Thạnh, TP.HCM", "Cơ sở 1: Quận 1, Cơ sở 2: Gò Vấp"], website: "https://vlu.edu.vn",
    description: "Đại học tư thục quy mô lớn: Thiết kế đồ họa, Kiến trúc, Truyền thông đa phương tiện, Quan hệ công chúng, Y khoa, Dược và Quản trị khách sạn.",
    scholarships: "Học bổng tài năng toàn phần và học bổng hỗ trợ nhập học sớm.",
    aliases: ["van lang", "dvl", "vlu", "vlu-sg", "dh van lang"],
  },
  {
    id: "hsu", slug: "truong-dai-hoc-hoa-sen", code: "HSU", name: "Trường Đại học Hoa Sen", shortName: "ĐH Hoa Sen",
    type: "tu-thuc", level: "dai-hoc", region: "nam", city: "TP. Hồ Chí Minh", founded: 1991, students: 15000, highlight: "Đại học chuẩn quốc tế NEAS (Úc) & ACBSP (Mỹ)",
    campuses: ["08 Nguyễn Văn Tráng, Bến Thành, Quận 1, TP.HCM", "Cơ sở Quang Trung, Thành Thái"], website: "https://hoasen.edu.vn",
    description: "Thế mạnh về Du lịch - Khách sạn, Kinh doanh quốc tế, Marketing, Thiết kế đồ họa, Thiết kế thời trang và Truyền thông.",
    scholarships: "Học bổng Tinh hoa Hoa Sen, học bổng doanh nhân tương lai.",
    aliases: ["hoa sen", "hsu", "dth", "dh hoa sen"],
  },

  // ── CAO ĐẲNG CHẤT LƯỢNG CAO TOÀN QUỐC ────────────────────────────────────
  {
    id: "cd-ckt", slug: "truong-cao-dang-ky-thuat-cao-thang", code: "CD-CKT", name: "Trường Cao đẳng Kỹ thuật Cao Thắng", shortName: "CĐ Kỹ thuật Cao Thắng",
    type: "cong-lap", level: "cao-dang", region: "nam", city: "TP. Hồ Chí Minh", founded: 1906, students: 10000, highlight: "Trường Cao đẳng Kỹ thuật số 1 Việt Nam, đạt chuẩn ABET (Mỹ)",
    campuses: ["65 Huỳnh Thúc Kháng, Bến Nghé, Quận 1, TP.HCM"], website: "https://caothang.edu.vn",
    description: "Cơ sở đào tạo thực hành kỹ thuật uy tín số 1 phía Nam: Công nghệ ô tô, Điện - Điện tử, Cơ điện tử, CNTT và Tự động hóa.",
    scholarships: "Học bổng khuyến khích học tập và tài trợ từ các tập đoàn công nghiệp (Toyota, Honda, Mitsubishi).",
    aliases: ["cao thang", "ckc", "cd cao thang", "cđ cao thang", "cd-ckt"],
  },
  {
    id: "cd-fpt-hcm", slug: "truong-cao-dang-fpt-polytechnic-tphcm", code: "CD-FPTHCM", name: "Trường Cao đẳng FPT Polytechnic TP.HCM", shortName: "CĐ FPT Polytechnic TP.HCM",
    type: "tu-thuc", level: "cao-dang", region: "nam", city: "TP. Hồ Chí Minh", founded: 2011, students: 20000, highlight: "Thực học – Thực nghiệp, cam kết việc làm",
    campuses: ["778/B1 Nguyễn Kiệm, Phú Nhuận, TP.HCM", "Cơ sở Quận 12 & Công viên phần mềm Quang Trung"], website: "https://caodang.fpt.edu.vn",
    description: "Đào tạo nghề thực chiến: Phát triển ứng dụng Web/Mobile, Thiết kế đồ họa số, Digital Marketing, Thương mại điện tử và Tự động hóa.",
    scholarships: "Học bổng khuyến học FPT Polytechnic.",
    aliases: ["cd fpt hcm", "fpt poly hcm", "polytechnic hcm", "cd-fpt-hcm"],
  },
  {
    id: "cd-dlsg", slug: "truong-cao-dang-du-lich-sai-gon", code: "CD-DLSG", name: "Trường Cao đẳng Du lịch Sài Gòn", shortName: "CĐ Du lịch Sài Gòn",
    type: "tu-thuc", level: "cao-dang", region: "nam", city: "TP. Hồ Chí Minh", founded: 1991, students: 6000, highlight: "Trường đào tạo chuyên sâu Du lịch & Nhà hàng Khách sạn phía Nam",
    campuses: ["347A Nguyễn Thượng Hiền, Phường 11, Quận 10, TP.HCM"], website: "https://dulichsaigon.edu.vn",
    description: "Đào tạo thực hành chuyên sâu Quản trị Khách sạn, Quản trị Lữ hành, Hướng dẫn viên du lịch quốc tế và Nghiệp vụ bàn bar.",
    scholarships: "Học bổng tài năng du lịch và cơ hội thực tập có lương tại các resort 5 sao Phú Quốc, Nha Trang.",
    aliases: ["cd dlsg", "cd du lich sai gon", "cđ du lich sai gon", "cd-dlsg"],
  },
  {
    id: "cd-ltt", slug: "truong-cao-dang-ly-tu-trong-tphcm", code: "CD-LTT", name: "Trường Cao đẳng Lý Tự Trọng TP.HCM", shortName: "CĐ Lý Tự Trọng TP.HCM",
    type: "cong-lap", level: "cao-dang", region: "nam", city: "TP. Hồ Chí Minh", founded: 1986, students: 12000, highlight: "Cơ sở đào tạo kỹ thuật thực hành quy mô lớn",
    campuses: ["390 Hoàng Văn Thụ, Phường 4, Tân Bình, TP.HCM"], website: "https://lttr.edu.vn",
    description: "Đào tạo nghề chuyên sâu: Công nghệ ô tô, Điện tử viễn thông, CNTT, Kế toán doanh nghiệp và Du lịch lữ hành.",
    scholarships: "Học bổng khuyến khích học nghề của UBND TP.HCM.",
    aliases: ["ltt", "cd ly tu trong", "cđ ly tu trong", "cd-ltt"],
  },
  {
    id: "cd-tdc", slug: "truong-cao-dang-cong-nghe-thu-duc", code: "CD-TDC", name: "Trường Cao đẳng Công nghệ Thủ Đức", shortName: "CĐ Công nghệ Thủ Đức",
    type: "cong-lap", level: "cao-dang", region: "nam", city: "TP. Hồ Chí Minh", founded: 1984, students: 9000, highlight: "Trường Cao đẳng nghề trọng điểm phía Nam",
    campuses: ["53 Võ Văn Ngân, Linh Chiểu, TP. Thủ Đức, TP.HCM"], website: "https://tdc.edu.vn",
    description: "Đào tạo nghề thực hành: Lập trình máy tính, Thiết kế đồ họa, Quản trị khách sạn, Cơ khí chế tạo và Điện tử công nghiệp.",
    scholarships: "Học bổng khuyến khích học nghề và tài trợ doanh nghiệp.",
    aliases: ["tdc", "cd thu duc", "cđ thu duc", "cao dang thu duc", "cd-tdc"],
  },
];

console.log(`✓ Validated nationalSchools: Total ${nationalSchools.length} schools.`);
